In [3]:
# import libraries
import numpy as np

In [6]:
# view version
print(np.__version__)

1.18.3


In [30]:
# Create Numpy ndarray Object
arr0 = np.array(72)            # 0-D Array or Scaler
print(arr0," - 0-D Array\n")

arr1 = np.array([1,2,3])   # 1-D Array or Vector
print(arr1," - 1-D Array\n")

arr2 = np.array([[1,2,3],[3,4,5]])   # 2-D Array or represent Matrix
print(arr2," - 2-D Array\n")

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3," - 3-D Array")


72  - 0-D Array

[1 2 3]  - 1-D Array

[[1 2 3]
 [3 4 5]]  - 2-D Array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]  - 3-D Array
